{"name": "test_file1_method1", "status": "failed", "statusDetails": {"message": "AssertionError: test failed\nassert 5 == 6", "trace": "def test_file1_method1():\n    \tx=5\n    \ty=6\n    \tassert x+1 == y,\"test failed\"\n>   \tassert x == y,\"test failed\"\nE    AssertionError: test failed\nE    assert 5 == 6\n\ntest_sample1.py:8: AssertionError"}, "start": 1574111199953, "stop": 1574111199954, "uuid": "838ed3b2-4e20-422c-8cf8-d6d76f43d106", "historyId": "eae324ad986dbe213175e0c74587e2a7", "fullName": "test_sample1#test_file1_method1", "labels": [{"name": "suite", "value": "test_sample1"}, {"name": "host", "value": "MBP-20142655.local"}, {"name": "thread", "value": "88619-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample1"}]}